[tasks.client-dev]
script = [
    "cd client/",
    "npm run dev"
]

[tasks.client-install]
script = [
    "cd client/",
    "npm install"
]

[tasks.server]
script = [
    "cargo build",
    "cargo run"
]
